---
galaxy_info:
  author: Nathaniel Felsen
  description: "Simple node Hello World"
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Amazon
    versions:
      - all
  categories:
    - web
dependencies: []
  
