---
# tasks file for awslogs

- name: install awslogs
  yum:
    name: awslogs
    state: present

- name: configre awslogs
  ini_file:
    path: /etc/awslogs/awslogs.conf
    section: general
    option: state_file
    value: /var/lib/awslogs/agent-state
  notify: restart awslogs

# - name: copy global configuration
#   copy:
#     src: awslogs.conf
#     dest: /etc/awslogs
#   notify: restart awslogs

# - name: copy custom configuration
#   copy:
#     src: "config/{{ item }}"
#     dest: /etc/awslogs/config/"{{ item }}"
#   notify: restart awslogs
#   with_items: config
#   tags: awslogs_config


- name: configre awslogs to collect {{ file }}
  ini_file:
    path: "/etc/awslogs/config/{{ name }}.conf"
    section: "{{ file }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: file, value: "{{ file }}" }
    - { option: log_group_name, value: "{{ file }}" }
    - { option: log_stream_name, value: "{instance_id}" }
    - { option: initial_position, value: "start_of_file" }
    - { option: buffer_duration, value: "5000" }
    - { option: datetime_format, value: "{{ datetime_format|default(%b %d %H:%M:%S) }}" }
  notify: restart awslogs

- name: start awslogs and enable it
  service:
    name: awslogs
    state: started
    enabled: yes
